fix syntax

diff --git a/.github/workflows/deploy-branch.yml b/.github/workflows/deploy-branch.yml
--- a/.github/workflows/deploy-branch.yml
+++ b/.github/workflows/deploy-branch.yml
@@ -6,7 +6,9 @@ on:
 run-name: Invalid main @${{ github.actor }}
 jobs:
   deploy:
-    - name: Skip main
-      run: |
-        echo "Cannot deploy from this branch. Use the branch selector in the dispatch window. "
-        exit 1
+    runs-on: ubuntu-latest
+    steps:
+      - name: Skip main
+        run: |
+          echo "Cannot deploy from this branch. Use the branch selector in the dispatch window. "
+          exit 1
